version: "3.9"  # optional since v1.27.0
services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_USER: "$POSTGRES_USER"
    volumes: 
      - pg:/var/lib/postgresql/data
  aleworld:
    image: yknx94/aleworld:1
    restart: always
    environment:
      DATABASE_URL: "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db/aleworld"
      SECRET_KEY_BASE: "$SECRET_KEY_BASE"
  techstacknews:
    image: yknx94/techstack-news:7
    restart: always
    environment:
      DATABASE_URL: "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db/techstacknews"
      SECRET_KEY_BASE: "$SECRET_KEY_BASE"
  nginx:
    image: nginx:1.20-alpine
    restart: always
    volumes: 
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports: 
      - 80:80
  db2:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_USER: "$POSTGRES_USER"
volumes:
  pg: {}