version: "3.9"  # optional since v1.27.0
services:
  aleworld:
    image: yknx94/aleworld:1
    restart: always
    environment:
      DATABASE_URL: "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@librecov.cvh1hkrwn6di.us-east-1.rds.amazonaws.com/aleworld"
      SECRET_KEY_BASE: "$SECRET_KEY_BASE"
  techstacknews:
    image: yknx94/techstack-news:13
    restart: always
    environment:
      DATABASE_URL: "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@librecov.cvh1hkrwn6di.us-east-1.rds.amazonaws.com/techstacknews"
      SECRET_KEY_BASE: "$SECRET_KEY_BASE"
  nginx:
    image: nginx:1.20-alpine
    restart: always
    volumes: 
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports: 
      - 80:80