apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: techstack-news-cert
spec:
  commonName: techstack.news
  secretName: techstack-news-cert
  dnsNames:
    - techstack.news
    - www.techstack.news
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer